using Cblx.Dynamics.Explorer.Client.Services.DynamicsServices;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Microsoft.Fast.Components.FluentUI;
using MudBlazor.Services;
var builder = WebAssemblyHostBuilder.CreateDefault(args);
var services = builder.Services;
services.AddMudServices();
services.AddFluentUIComponents();
services.AddScoped(_ => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
services.AddDynamicsServices();
await builder.Build().RunAsync();
